### PUT request to update an existing patient entity

PUT http://localhost:4000/patients/ab3d2398-9994-4a32-a207-c3dcece6e914
Content-Type: application/json

{
  "name": "Jhony Deep Doo updated success",
  "email": "jhonydeepdooupdated@gmail.com",
  "address": "12345 Street LA",
  "dateOfBirth": "1995-09-09"
}

###